"""Async REST + WebSocket client for the Z-Wave Alarm service."""

from .client import (
    async_arm,
    async_assign_sensor,
    async_create_ha_link,
    async_create_user,
    async_create_zone,
    async_delete_ha_link,
    async_delete_user,
    async_disarm,
    async_get_events,
    async_get_lockout_policy,
    async_get_panel_state,
    async_get_zones,
    async_list_users,
    async_login,
    async_logout,
    async_update_lockout_policy,
    async_validate_connection,
)
from .errors import (
    AccountLocked,
    BadRequest,
    CannotConnect,
    CommandRejected,
    Conflict,
    Forbidden,
    InvalidAuth,
    NotFound,
    ServiceUnavailable,
    TooManyRequests,
    ZwaveAlarmError,
)
from .stream import async_stream_events

__all__ = [
    "AccountLocked",
    "BadRequest",
    "CannotConnect",
    "CommandRejected",
    "Conflict",
    "Forbidden",
    "InvalidAuth",
    "NotFound",
    "ServiceUnavailable",
    "TooManyRequests",
    "ZwaveAlarmError",
    "async_arm",
    "async_assign_sensor",
    "async_create_ha_link",
    "async_create_user",
    "async_create_zone",
    "async_delete_ha_link",
    "async_delete_user",
    "async_disarm",
    "async_get_events",
    "async_get_lockout_policy",
    "async_get_panel_state",
    "async_get_zones",
    "async_list_users",
    "async_login",
    "async_logout",
    "async_stream_events",
    "async_update_lockout_policy",
    "async_validate_connection",
]
